import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { TOWNS_BY_COUNTY } from '../src/data/irishTowns.js';
import { TOWNS_BY_COUNTY_SPAIN } from '../src/data/spainTowns.js';
import { TOWNS_BY_COUNTY_ENGLAND } from '../src/data/englandTowns.js';
import { TOWNS_BY_COUNTY_FRANCE } from '../src/data/franceTowns.js';
import { TOWNS_BY_COUNTY_PORTUGAL } from '../src/data/portugalTowns.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const DATA: Record<string, Record<string, string[]>> = {
  ireland: TOWNS_BY_COUNTY,
  spain: TOWNS_BY_COUNTY_SPAIN,
  england: TOWNS_BY_COUNTY_ENGLAND,
  france: TOWNS_BY_COUNTY_FRANCE,
  portugal: TOWNS_BY_COUNTY_PORTUGAL,
};

const STATIC_PAGES: Record<string, string[]> = {
  ireland: ['/', '/about-us', '/services', '/pricing', '/faq', '/contact-us', '/locations', '/catalogue', '/news', '/blog', '/hire-agent'],
  england: ['/', '/about-us', '/services', '/pricing', '/epc-faq', '/contact-us', '/locations', '/catalogue', '/news', '/blog', '/hire-agent'],
  spain: ['/', '/sobre-nosotros', '/servicios', '/precios', '/preguntas-frecuentes', '/contacto', '/ubicaciones', '/directorio', '/noticias', '/blog', '/asesor-energetico', '/pedir-presupuesto'],
  france: ['/', '/about-us', '/services', '/pricing', '/ber-faqs', '/contact-us', '/locations', '/catalogue', '/news', '/blog', '/hire-agent'],
  portugal: ['/', '/about-us', '/services', '/pricing', '/faq', '/contact-us', '/locations', '/catalogue', '/news', '/blog', '/hire-agent'],
};

const COUNTY_PREFIX: Record<string, string> = {
  spain: 'certificado-energetico-',
  england: 'epc-assessment-',
};

const ENGLAND_FRIENDLY_COUNTIES: Record<string, string> = {
  'Greater London': 'london',
  'Greater Manchester': 'manchester',
  'West Midlands': 'birmingham',
  'West Yorkshire': 'leeds',
  'Merseyside': 'liverpool',
  'South Yorkshire': 'sheffield',
  'Nottinghamshire': 'nottingham',
  'Leicestershire': 'leicester',
  'Northumberland': 'newcastle',
  'Hampshire': 'southampton',
  'Oxfordshire': 'oxford',
};

function slugify(text: string): string {
  return text
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

function countySlug(tenant: string, county: string): string {
  if (tenant === 'england' && ENGLAND_FRIENDLY_COUNTIES[county]) {
    return ENGLAND_FRIENDLY_COUNTIES[county];
  }
  return slugify(county);
}

function generatePaths(tenant: string): string[] {
  const paths = new Set<string>(STATIC_PAGES[tenant] || STATIC_PAGES.ireland);
  const data = DATA[tenant] || {};
  const prefix = COUNTY_PREFIX[tenant] || '';

  Object.entries(data).forEach(([county, towns]) => {
    const cSlug = countySlug(tenant, county);
    paths.add(`/${prefix}${cSlug}`);
    towns.forEach(town => {
      const tSlug = slugify(town);
      paths.add(`/${prefix}${cSlug}/${tSlug}`);
    });
  });

  return [...paths].sort((a, b) => a.localeCompare(b));
}

const SITEMAP_BY_TENANT: Record<string, string[]> = {};
Object.keys(DATA).forEach(tenant => {
  SITEMAP_BY_TENANT[tenant] = generatePaths(tenant);
});

const output = `// Auto-generated by scripts/generate-sitemap-data.ts
// Run: npx tsc scripts/generate-sitemap-data.ts --outDir .tmp-smap --module ESNext --target ES2022 --moduleResolution bundler --skipLibCheck --declaration false --esModuleInterop && node .tmp-smap/scripts/generate-sitemap-data.js
export const SITEMAP_BY_TENANT = ${JSON.stringify(SITEMAP_BY_TENANT)};
`;

const outPath = path.join(__dirname, '..', 'sitemap-data.js');
fs.writeFileSync(outPath, output);

Object.entries(SITEMAP_BY_TENANT).forEach(([tenant, paths]) => {
  console.log(`${tenant}: ${paths.length} URLs`);
});
console.log(`\nSaved to: ${outPath}`);
